export const destination = [
  ["Albania", "Elbasan"],
  ["Andora", "Andorra la Vella"],
  ["Austria", "Graz", "Innsbruck", "Klagenfurt am Worthersee", "Linz", "Salzburg", "Vienna"],
  ["Belgia", "Antwerp", "Brussels", "Liege"],
  ["Bośnia i Hercegowina", "Banja Luka", "Doboj", "Lukavac", "Mostar", "Sarajevo", "Zenica"],
  [
    "Bułgaria",
    "Blagoevgrad",
    "Burgas",
    "Karlovo",
    "Kozloduy",
    "Montana",
    "Pernik",
    "Pirdop",
    "Pleven",
    "Plovdiv",
    "Ruse",
    "Sofia",
    "Varna",
    "Veliko Tarnovo",
    "Vidin",
  ],
];
